version: '3.8'

services:
    app:
        build:
            context: .
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: pg-database
        environment:
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: laravel_db
        ports:
            - "5432:5432"

    queue:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
